#!/bin/bash
echo $(pwd)
docker run \
--gpus all \
-it \
--rm \
--name=tf-spiking-neuron \
-p 0.0.0.0:23:22 \
--runtime=nvidia \
-v "$(pwd)":/tensorflow \
-v /media/internal/record/tfspikingnn:/record \
-v /var/log:/log \
louisross/tensorflow:1.0 \
bash
